# Generated by Django 5.0.1 on 2024-03-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_image', models.ImageField(upload_to='images/')),
                ('artist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.artist_table')),
            ],
        ),
    ]
