# Generated by Django 4.2.11 on 2024-04-24 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieplaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=150)),
                ('movie_image', models.ImageField(upload_to='movies/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='playlist/default.png', upload_to='playlist/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='songadd',
            name='song_movie',
        ),
        migrations.AddField(
            model_name='artist_table',
            name='artist_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songadd',
            name='song_singers',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='playlistadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.playlist')),
                ('song1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.songadd')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='movieplaylistadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mplaylist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.movieplaylist')),
                ('song2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.songadd')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artistimage/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.artist_table')),
            ],
        ),
        migrations.AlterField(
            model_name='songadd',
            name='song_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.artist_add'),
        ),
    ]
