# Generated by Django 4.2.11 on 2024-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0002_movieplaylist_playlist_remove_songadd_song_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='watch_it',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
