# Generated by Django 4.2.11 on 2024-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0003_notification_watch_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='watch_it',
            field=models.URLField(max_length=500),
        ),
    ]
