# Generated by Django 5.0.1 on 2024-03-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0003_alter_artist_table_artist_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
