# Generated by Django 4.2.11 on 2024-05-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0004_alter_notification_watch_it'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='watch_it',
        ),
    ]
