# Generated by Django 5.0.1 on 2024-03-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playerapp.artist_table')),
            ],
        ),
    ]
