# Generated by Django 5.0.1 on 2024-03-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0006_artist_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='artist_add',
        ),
    ]
