# Generated by Django 5.0.1 on 2024-03-29 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0007_delete_artist_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='playerapp.artist_table')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='playerapp.artist_table')),
            ],
        ),
    ]
