# Generated by Django 5.0.1 on 2024-03-29 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0008_artist_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_add',
            name='image',
            field=models.ImageField(upload_to='artistimage/'),
        ),
        migrations.AlterField(
            model_name='artist_add',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.artist_table'),
        ),
    ]
