# Generated by Django 5.0.1 on 2024-04-04 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0009_alter_artist_add_image_alter_artist_add_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songadd',
            name='song_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.artist_add'),
        ),
        migrations.AlterField(
            model_name='songadd',
            name='song_movie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='songadd',
            name='song_singers',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='playlist/default.png', upload_to='playlist/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='playlistadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.playlist')),
                ('song1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.songadd')),
            ],
        ),
    ]
