# Generated by Django 5.0.1 on 2024-03-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0009_alter_artist_add_image_alter_artist_add_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songadd',
            name='song_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.artist_add'),
        ),
    ]
