# Generated by Django 5.0.1 on 2024-04-06 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0010_alter_songadd_song_artist_alter_songadd_song_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistadd',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
