# Generated by Django 4.2.11 on 2024-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0011_playlistadd_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieplaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=150)),
                ('movie_image', models.ImageField(upload_to='movies/')),
            ],
        ),
    ]
