# Generated by Django 4.2.11 on 2024-04-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0013_movieplaylist_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songadd',
            name='song_movie',
        ),
    ]
