# Generated by Django 4.2.11 on 2024-04-08 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0014_remove_songadd_song_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieplaylistadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mplaylist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.movieplaylist')),
                ('song2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.songadd')),
            ],
        ),
    ]
