# Generated by Django 4.2.11 on 2024-04-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0016_remove_playlistadd_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieplaylistadd',
            name='artist',
        ),
    ]
