# Generated by Django 4.2.11 on 2024-04-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0017_remove_movieplaylistadd_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='mlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.songadd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerapp.artist_table')),
            ],
        ),
    ]
