# Generated by Django 4.2.11 on 2024-04-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0019_alter_mlist_song3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mlist',
        ),
    ]
