# Generated by Django 4.2.11 on 2024-04-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0020_delete_mlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist_add',
            name='image',
        ),
    ]
